name: CI Logic test

on:
  pull_request:
    branches: [master]

  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Nodejs
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - run: npm install -g yarn
    
    - run: |
        cd LogicTest
        yarn
        yarn test:coverage
